version: '2'

services:
   db:
     image: mysql:5.7
     volumes:
       - ~/estudo/todo-user/containers/data:/var/lib/mysql
     restart: always
     ports:
      - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: crud_user